//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinisterWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keywords
    {
        public int KeywordId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SinisterType_fk { get; set; }
    
        public virtual SinisterTypes SinisterTypes { get; set; }
    }
}
