//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinisterWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keywords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Keywords()
        {
            this.SinisterKeywords = new HashSet<SinisterKeywords>();
        }
    
        public int KeywordId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SinisterTypeId { get; set; }
    
        public virtual SinisterTypes SinisterTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinisterKeywords> SinisterKeywords { get; set; }
    }
}
