//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinisterWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinisterKeywords
    {
        public int SinisterKeywordId { get; set; }
        public Nullable<int> KeywordId_fk { get; set; }
        public Nullable<int> SinisterId_fk { get; set; }
    
        public virtual Keywords Keywords { get; set; }
        public virtual Sinisters Sinisters { get; set; }
    }
}
