//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinisterWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinisters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinisters()
        {
            this.SinisterLob = new HashSet<SinisterLob>();
            this.SinisterKeywords = new HashSet<SinisterKeywords>();
        }
    
        public int SinisterId { get; set; }
        public Nullable<int> Clientid { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> SinisterTypeId { get; set; }
        public Nullable<int> ActivitySectorId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> DestructionLevelId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> LoBId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Consequence { get; set; }
        public string FileOrigine { get; set; }
        public string FileName { get; set; }
        public string AggravatingFactor { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> SinisterStatusId { get; set; }
    
        public virtual ActivitySectors ActivitySectors { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual DestructionLevels DestructionLevels { get; set; }
        public virtual Documents Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinisterLob> SinisterLob { get; set; }
        public virtual SinisterStatus SinisterStatus { get; set; }
        public virtual Sites Sites { get; set; }
        public virtual Users Users { get; set; }
        public virtual SinisterTypes SinisterTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinisterKeywords> SinisterKeywords { get; set; }
    }
}
