//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinisterWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Sinisters = new HashSet<Sinisters>();
        }
    
        public int Userid { get; set; }

        [DisplayName("Jamie Id")]
        public string EmployeeID { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RoleId { get; set; }

        [DisplayName("Last name")]
        public string LastName { get; set; }

        [DisplayName("First name")]
        public string FirstName { get; set; }

        [DisplayName("Contact")]
        public string Email { get; set; }

        [DisplayName("Jamie user name")]
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinisters> Sinisters { get; set; }
    }
}
